target( "Resources" )
  set_kind( "phony" )

  set_default( false )
  set_group( "RESOURCES" )

  --add_files( "Audio/**" )
  --add_files( "Fonts/**" )
  --add_files( "Img/**" )
  --add_files( "Maps/**" )

  after_build( function ( target )
    import( "core.project.config" )
    os.mkdir( path.join( path.join( "$(projectdir)", target.targetdir( target ) ), "Resources" ) )
    os.cp( path.join( "$(scriptdir)", "Audio" ), path.join( path.join( "$(projectdir)", target.targetdir( target ) ), "Resources" ) )
    os.cp( path.join( "$(scriptdir)", "Fonts" ), path.join( path.join( "$(projectdir)", target.targetdir( target ) ), "Resources" ) )
    os.cp( path.join( "$(scriptdir)", "Img" ), path.join( path.join( "$(projectdir)", target.targetdir( target ) ), "Resources" ) )
    os.cp( path.join( "$(scriptdir)", "Maps" ), path.join( path.join( "$(projectdir)", target.targetdir( target ) ), "Resources" ) )
  end )
  after_install( function ( target )
    import( "core.project.config" )
    os.mkdir( path.join( target.installdir( target ), "Resources" ) )
    os.cp( path.join( "$(scriptdir)", "Audio" ), path.join( target.installdir( target ), "Resources" ) )
    os.cp( path.join( "$(scriptdir)", "Fonts" ), path.join( target.installdir( target ), "Resources" ) )
    os.cp( path.join( "$(scriptdir)", "Img" ), path.join( target.installdir( target ), "Resources" ) )
    os.cp( path.join( "$(scriptdir)", "Maps" ), path.join( target.installdir( target ), "Resources" ) )
  end )
  after_installcmd( function ( target )
    import( "core.project.config" )
    os.mkdir( path.join( target.installdir( target ), "Resources" ) )
    os.cp( path.join( "$(scriptdir)", "Audio" ), path.join( target.installdir( target ), "Resources" ) )
    os.cp( path.join( "$(scriptdir)", "Fonts" ), path.join( target.installdir( target ), "Resources" ) )
    os.cp( path.join( "$(scriptdir)", "Img" ), path.join( target.installdir( target ), "Resources" ) )
    os.cp( path.join( "$(scriptdir)", "Maps" ), path.join( target.installdir( target ), "Resources" ) )
  end )
